import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

// ... existing PDF functions ...

// Basic school info used in report headers/footers. Read from env with defaults.
const getSchoolInfo = () => ({
  name: (import.meta.env.VITE_SCHOOL_NAME as string) || 'Schomas School',
  address: (import.meta.env.VITE_SCHOOL_ADDRESS as string) || '123 Academy Lane, City, Country',
  phone: (import.meta.env.VITE_SCHOOL_PHONE as string) || '+1 (555) 123-4567',
  email: (import.meta.env.VITE_SCHOOL_EMAIL as string) || 'info@schomas.com',
  website: (import.meta.env.VITE_SCHOOL_WEBSITE as string) || 'www.schomas.com',
});

// Returns options to pass into autoTable to draw a classic header and footer on each page.
const addPdfHeaderFooterOptions = (doc: any) => {
  const school = getSchoolInfo();
  return {
    didDrawPage: (data: any) => {
      // Header
      doc.setFontSize(14);
      doc.setFont(undefined, 'bold');
      doc.text(school.name, 14, 16);
      doc.setFontSize(9);
      doc.setFont(undefined, 'normal');
      const contact = `${school.address} | Phone: ${school.phone} | ${school.email} | ${school.website}`;
      const maxWidth = (doc.internal.pageSize as any).width - 28;
      const split = doc.splitTextToSize(contact, maxWidth);
      doc.text(split, 14, 22);

      // Footer
      const pageSize = doc.internal.pageSize;
      const pageWidth = pageSize.getWidth ? pageSize.getWidth() : pageSize.width;
      const pageHeight = pageSize.getHeight ? pageSize.getHeight() : pageSize.height;
      doc.setFontSize(8);
      doc.setTextColor(120);
      doc.text(`Generated by Schomas • ${new Date().toLocaleString()}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
      doc.setTextColor(0);
    },
    margin: { top: 36 },
  };
};

const generateStudentsExcel = (data: any[]) => {
  try {
    const school = getSchoolInfo();
    const headerRows = [
      [school.name],
      [school.address],
      [`Phone: ${school.phone}  Email: ${school.email}  Website: ${school.website}`],
      [],
    ];

    const dataRows = data.map(item => [
      item.studentHumanId || item.studentId || 'N/A',
      item.name || 'N/A',
      item.gender || 'N/A',
      item.className || 'N/A',
      item.grade || 'N/A',
      item.address || 'N/A',
      item.dateOfBirth ? new Date(item.dateOfBirth).toLocaleDateString() : 'N/A',
      item.age ?? 'N/A',
      item.enrollmentDate ? new Date(item.enrollmentDate).toLocaleDateString() : 'N/A',
      item.status || 'N/A',
      item.owesBooks || 'NO',
    ]);

    const aoa = [
      ...headerRows,
      ['Student ID', 'Name', 'Gender', 'Class', 'Grade', 'Address', 'Date of Birth', 'Age', 'Enrollment Date', 'Status', 'Owes Books'],
      ...dataRows,
    ];

    const ws = XLSX.utils.aoa_to_sheet(aoa as any);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Students');
    XLSX.writeFile(wb, 'students-report.xlsx');
  } catch (error) {
    console.error('Error generating students Excel:', error);
    throw new Error('Failed to generate students Excel report');
  }
};

const generateTeachersExcel = (data: any[]) => {
  try {
    const school = getSchoolInfo();
    const headerRows = [[school.name], [school.address], [`Phone: ${school.phone}  Email: ${school.email}  Website: ${school.website}`], []];
    const dataRows = data.map(item => [
      item.name || 'N/A',
      item.gender || 'N/A',
      item.email || 'N/A',
      item.phoneNumber || 'N/A',
      item.qualification || 'N/A',
      item.yearsOfExperience ?? 'N/A',
      item.address || 'N/A',
      item.dateOfBirth ? new Date(item.dateOfBirth).toLocaleDateString() : 'N/A',
      item.hireDate ? new Date(item.hireDate).toLocaleDateString() : (item.joinDate ? new Date(item.joinDate).toLocaleDateString() : 'N/A'),
      item.status || 'N/A',
      item.className || 'N/A',
      item.subjectSpecialization || 'N/A',
    ]);

    const aoa = [
      ...headerRows,
      ['Name', 'Gender', 'Email', 'Phone', 'Qualification', 'Years Exp', 'Address', 'Date of Birth', 'Hire Date', 'Status', 'Class', 'Specialization'],
      ...dataRows,
    ];

    const ws = XLSX.utils.aoa_to_sheet(aoa as any);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Teachers');
    XLSX.writeFile(wb, 'teachers-report.xlsx');
  } catch (error) {
    console.error('Error generating teachers Excel:', error);
    throw new Error('Failed to generate teachers Excel report');
  }
};

const generateCoursesExcel = (data: any[]) => {
  try {
    const school = getSchoolInfo();
    const headerRows = [[school.name], [school.address], [`Phone: ${school.phone}  Email: ${school.email}`], []];
    const dataRows = data.map(item => [
      item.name || 'N/A',
      item.code || 'N/A',
      item.className || 'N/A',
      item.teacherName || 'N/A',
      item.department || 'N/A',
      item.credits || 0,
      item.enrollmentCount || 0,
      item.status || 'N/A',
      item.active === true ? 'YES' : 'NO',
    ]);
    const aoa = [
      ...headerRows,
      ['Name', 'Code', 'Class', 'Teacher', 'Department', 'Credits', 'Enrollment Count', 'Status', 'Active'],
      ...dataRows,
    ];
    const ws = XLSX.utils.aoa_to_sheet(aoa as any);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Courses');
    XLSX.writeFile(wb, 'courses-report.xlsx');
  } catch (error) {
    console.error('Error generating courses Excel:', error);
    throw new Error('Failed to generate courses Excel report');
  }
};

const generateEnrollmentsExcel = (data: any[]) => {
  try {
    const school = getSchoolInfo();
    const headerRows = [[school.name], [school.address], [`Phone: ${school.phone}  Email: ${school.email}`], []];
    const dataRows = data.map(item => [
      item.studentHumanId || item.studentId || 'N/A',
      item.studentName || 'N/A',
      item.courseName || 'N/A',
      item.className || 'N/A',
      item.enrollmentDate ? new Date(item.enrollmentDate).toLocaleDateString() : 'N/A',
      item.status || 'N/A',
      item.termName || 'N/A',
      item.academicYearName || 'N/A',
    ]);
    const aoa = [
      ...headerRows,
      ['Student ID', 'Student', 'Course', 'Class', 'Enrollment Date', 'Status', 'Term', 'Academic Year'],
      ...dataRows,
    ];
    const ws = XLSX.utils.aoa_to_sheet(aoa as any);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Enrollments');
    XLSX.writeFile(wb, 'enrollments-report.xlsx');
  } catch (error) {
    console.error('Error generating enrollments Excel:', error);
    throw new Error('Failed to generate enrollments Excel report');
  }
};

const generateFeePaymentsExcel = (data: any[]) => {
  try {
    const school = getSchoolInfo();
    const headerRows = [[school.name], [school.address], [`Phone: ${school.phone}  Email: ${school.email}`], []];
    const dataRows = data.map(item => [
      item.studentHumanId || item.studentId || 'N/A',
      item.studentName || 'N/A',
      item.className || 'N/A',
      item.amount ? `$${item.amount.toLocaleString()}` : 'N/A',
      item.paymentDate ? new Date(item.paymentDate).toLocaleDateString() : 'N/A',
      item.paymentMethod || 'N/A',
      item.status || 'N/A',
      item.termName || 'N/A',
    ]);
    const aoa = [
      ...headerRows,
      ['Student ID', 'Student', 'Class', 'Amount', 'Payment Date', 'Payment Method', 'Status', 'Term'],
      ...dataRows,
    ];
    const ws = XLSX.utils.aoa_to_sheet(aoa as any);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Fee Payments');
    XLSX.writeFile(wb, 'fee-payments-report.xlsx');
  } catch (error) {
    console.error('Error generating fee payments Excel:', error);
    throw new Error('Failed to generate fee payments Excel report');
  }
};

const generateComprehensiveExcel = (data: {
  students: any[];
  teachers: any[];
  courses: any[];
  enrollments: any[];
  feePayments: any[];
}) => {
  try {
    const wb = XLSX.utils.book_new();

    const studentsWs = XLSX.utils.json_to_sheet(
      data.students.map(item => ({
        'Student ID': item.studentHumanId || item.studentId || 'N/A',
        Name: item.name || 'N/A',
        Gender: item.gender || 'N/A',
        Class: item.className || 'N/A',
        Grade: item.grade || 'N/A',
        Address: item.address || 'N/A',
        'Date of Birth': item.dateOfBirth ? new Date(item.dateOfBirth).toLocaleDateString() : 'N/A',
        Age: item.age ?? 'N/A',
        'Enrollment Date': item.enrollmentDate ? new Date(item.enrollmentDate).toLocaleDateString() : 'N/A',
        Status: item.status || 'N/A',
        'Owes Books': item.owesBooks || 'NO',
      }))
    );
    XLSX.utils.book_append_sheet(wb, studentsWs, 'Students');

    const teachersWs = XLSX.utils.json_to_sheet(
      data.teachers.map(item => ({
        Name: item.name || 'N/A',
        Gender: item.gender || 'N/A',
        Email: item.email || 'N/A',
        Phone: item.phoneNumber || 'N/A',
        Qualification: item.qualification || 'N/A',
        'Years Exp': item.yearsOfExperience ?? 'N/A',
        Address: item.address || 'N/A',
        'Date of Birth': item.dateOfBirth ? new Date(item.dateOfBirth).toLocaleDateString() : 'N/A',
        'Hire Date': item.hireDate ? new Date(item.hireDate).toLocaleDateString() : (item.joinDate ? new Date(item.joinDate).toLocaleDateString() : 'N/A'),
        Status: item.status || 'N/A',
        Class: item.className || 'N/A',
        Specialization: item.subjectSpecialization || 'N/A',
      }))
    );
    XLSX.utils.book_append_sheet(wb, teachersWs, 'Teachers');

    const coursesWs = XLSX.utils.json_to_sheet(
      data.courses.map(item => ({
        Name: item.name || 'N/A',
        Code: item.code || 'N/A',
        Class: item.className || 'N/A',
        Teacher: item.teacherName || 'N/A',
        Department: item.department || 'N/A',
        Credits: item.credits || 0,
        'Enrollment Count': item.enrollmentCount || 0,
        Status: item.status || 'N/A',
        Active: item.active === true ? 'YES' : 'NO',
      }))
    );
    XLSX.utils.book_append_sheet(wb, coursesWs, 'Courses');

    const enrollmentsWs = XLSX.utils.json_to_sheet(
      data.enrollments.map(item => ({
        'Student ID': item.studentHumanId || item.studentId || 'N/A',
        Student: item.studentName || 'N/A',
        Course: item.courseName || 'N/A',
        Class: item.className || 'N/A',
        'Enrollment Date': item.enrollmentDate ? new Date(item.enrollmentDate).toLocaleDateString() : 'N/A',
        Status: item.status || 'N/A',
        Term: item.termName || 'N/A',
        AcademicYear: item.academicYearName || 'N/A',
      }))
    );
    XLSX.utils.book_append_sheet(wb, enrollmentsWs, 'Enrollments');

    const feePaymentsWs = XLSX.utils.json_to_sheet(
      data.feePayments.map(item => ({
        'Student ID': item.studentHumanId || item.studentId || 'N/A',
        Student: item.studentName || 'N/A',
        Class: item.className || 'N/A',
        Amount: item.amount ? `$${item.amount.toLocaleString()}` : 'N/A',
        'Payment Date': item.paymentDate ? new Date(item.paymentDate).toLocaleDateString() : 'N/A',
        'Payment Method': item.paymentMethod || 'N/A',
        Status: item.status || 'N/A',
        Term: item.termName || 'N/A',
      }))
    );
    XLSX.utils.book_append_sheet(wb, feePaymentsWs, 'Fee Payments');

    XLSX.writeFile(wb, 'comprehensive-report.xlsx');
  } catch (error) {
    console.error('Error generating comprehensive Excel:', error);
    throw new Error('Failed to generate comprehensive Excel report');
  }
};


// Initialize jsPDF with autoTable and generate PDF reports
const generateStudentsPDF = (data: any[]) => {
  try {
    const doc: any = new jsPDF();
    const headerFooterOpts = addPdfHeaderFooterOptions(doc);
    autoTable(doc, {
      head: [['Student ID', 'Name', 'Gender', 'Class', 'Address', 'DOB', 'Age', 'Status', 'Owes Books']],
      body: data.map(item => [
        item.studentHumanId || item.studentId || 'N/A',
        item.name || 'N/A',
        item.gender || 'N/A',
        item.className || 'N/A',
        item.address || 'N/A',
        item.dateOfBirth ? new Date(item.dateOfBirth).toLocaleDateString() : 'N/A',
        item.age ?? 'N/A',
        item.status || 'N/A',
        item.owesBooks || 'NO',
      ]),
      startY: 36,
      ...headerFooterOpts,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [66, 139, 202] },
    });
    doc.save('students-report.pdf');
  } catch (error) {
    console.error('Error generating students PDF:', error);
    throw new Error('Failed to generate students PDF report');
  }
};

const generateTeachersPDF = (data: any[]) => {
  try {
    const doc: any = new jsPDF();
    const headerFooterOpts = addPdfHeaderFooterOptions(doc);
    autoTable(doc, {
      head: [['Name', 'Gender', 'Phone', 'Qualification', 'Years Exp', 'Address', 'DOB', 'Hire Date', 'Status']],
      body: data.map(item => [
        item.name || 'N/A',
        item.gender || 'N/A',
        item.phoneNumber || 'N/A',
        item.qualification || 'N/A',
        item.yearsOfExperience ?? 'N/A',
        item.address || 'N/A',
        item.dateOfBirth ? new Date(item.dateOfBirth).toLocaleDateString() : 'N/A',
        item.hireDate ? new Date(item.hireDate).toLocaleDateString() : (item.joinDate ? new Date(item.joinDate).toLocaleDateString() : 'N/A'),
        item.status || 'N/A',
      ]),
      startY: 36,
      ...headerFooterOpts,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [66, 139, 202] },
    });
    doc.save('teachers-report.pdf');
  } catch (error) {
    console.error('Error generating teachers PDF:', error);
    throw new Error('Failed to generate teachers PDF report');
  }
};

const generateCoursesPDF = (data: any[]) => {
  try {
    const doc: any = new jsPDF();
    const headerFooterOpts = addPdfHeaderFooterOptions(doc);
    autoTable(doc, {
      head: [['Name', 'Code', 'Class', 'Teacher', 'Department', 'Credits', 'Enrollment', 'Status', 'Active']],
      body: data.map(item => [
        item.name || 'N/A',
        item.code || 'N/A',
        item.className || 'N/A',
        item.teacherName || 'N/A',
        item.department || 'N/A',
        item.credits || 0,
        item.enrollmentCount || 0,
        item.status || 'N/A',
        item.active === true ? 'YES' : 'NO',
      ]),
      startY: 36,
      ...headerFooterOpts,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [66, 139, 202] },
    });
    doc.save('courses-report.pdf');
  } catch (error) {
    console.error('Error generating courses PDF:', error);
    throw new Error('Failed to generate courses PDF report');
  }
};

const generateEnrollmentsPDF = (data: any[]) => {
  try {
    const doc: any = new jsPDF();
    const headerFooterOpts = addPdfHeaderFooterOptions(doc);
    autoTable(doc, {
      head: [['Student ID', 'Student', 'Course', 'Class', 'Enrollment Date', 'Status', 'Term', 'Academic Year']],
      body: data.map(item => [
        item.studentHumanId || item.studentId || 'N/A',
        item.studentName || 'N/A',
        item.courseName || 'N/A',
        item.className || 'N/A',
        item.enrollmentDate ? new Date(item.enrollmentDate).toLocaleDateString() : 'N/A',
        item.status || 'N/A',
        item.termName || 'N/A',
        item.academicYearName || 'N/A',
      ]),
      startY: 36,
      ...headerFooterOpts,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [66, 139, 202] },
    });
    doc.save('enrollments-report.pdf');
  } catch (error) {
    console.error('Error generating enrollments PDF:', error);
    throw new Error('Failed to generate enrollments PDF report');
  }
};

const generateFeePaymentsPDF = (data: any[]) => {
  try {
    const doc: any = new jsPDF();
    const headerFooterOpts = addPdfHeaderFooterOptions(doc);
    autoTable(doc, {
      head: [['Student ID', 'Student', 'Class', 'Amount', 'Payment Date', 'Payment Method', 'Status', 'Term']],
      body: data.map(item => [
        item.studentHumanId || item.studentId || 'N/A',
        item.studentName || item.studentName || 'N/A',
        item.className || 'N/A',
        item.amount ? `$${item.amount.toLocaleString()}` : 'N/A',
        item.paymentDate ? new Date(item.paymentDate).toLocaleDateString() : 'N/A',
        item.paymentMethod || 'N/A',
        item.status || 'N/A',
        item.termName || 'N/A',
      ]),
      startY: 36,
      ...headerFooterOpts,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [66, 139, 202] },
    });
    doc.save('fee-payments-report.pdf');
  } catch (error) {
    console.error('Error generating fee payments PDF:', error);
    throw new Error('Failed to generate fee payments PDF report');
  }
};

const generateComprehensivePDF = (data: {
  students: any[];
  teachers: any[];
  courses: any[];
  enrollments: any[];
  feePayments: any[];
}) => {
  try {
    const doc: any = new jsPDF();
    const headerFooterOpts = addPdfHeaderFooterOptions(doc);

    // Students Table
    doc.text('Students Report', 14, 24);
    autoTable(doc, {
      head: [['Student ID', 'Name', 'Gender', 'Class', 'Address', 'DOB', 'Age', 'Status', 'Owes Books']],
      body: data.students.map(item => [
        item.studentHumanId || item.studentId || 'N/A',
        item.name || 'N/A',
        item.gender || 'N/A',
        item.className || 'N/A',
        item.address || 'N/A',
        item.dateOfBirth ? new Date(item.dateOfBirth).toLocaleDateString() : 'N/A',
        item.age ?? 'N/A',
        item.status || 'N/A',
        item.owesBooks || 'NO',
      ]),
      startY: 36,
      ...headerFooterOpts,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [66, 139, 202] },
    });

    // Teachers Table
    doc.text('Teachers Report', 14, (doc as any).lastAutoTable.finalY + 14);
    autoTable(doc, {
      head: [['Name', 'Gender', 'Phone', 'Qualification', 'Years Exp', 'Address', 'DOB', 'Hire Date', 'Status']],
      body: data.teachers.map(item => [
        item.name || 'N/A',
        item.gender || 'N/A',
        item.phoneNumber || 'N/A',
        item.qualification || 'N/A',
        item.yearsOfExperience ?? 'N/A',
        item.address || 'N/A',
        item.dateOfBirth ? new Date(item.dateOfBirth).toLocaleDateString() : 'N/A',
        item.hireDate ? new Date(item.hireDate).toLocaleDateString() : (item.joinDate ? new Date(item.joinDate).toLocaleDateString() : 'N/A'),
        item.status || 'N/A',
      ]),
      startY: (doc as any).lastAutoTable.finalY + 20,
      ...headerFooterOpts,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [66, 139, 202] },
    });

    // Courses Table
    doc.text('Courses Report', 14, (doc as any).lastAutoTable.finalY + 14);
    autoTable(doc, {
      head: [['Name', 'Code', 'Class', 'Teacher', 'Department', 'Credits', 'Enrollment', 'Status', 'Active']],
      body: data.courses.map(item => [
        item.name || 'N/A',
        item.code || 'N/A',
        item.className || 'N/A',
        item.teacherName || 'N/A',
        item.department || 'N/A',
        item.credits || 0,
        item.enrollmentCount || 0,
        item.status || 'N/A',
        item.active === true ? 'YES' : 'NO',
      ]),
      startY: (doc as any).lastAutoTable.finalY + 20,
      ...headerFooterOpts,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [66, 139, 202] },
    });

    // Enrollments Table
    doc.text('Enrollments Report', 14, (doc as any).lastAutoTable.finalY + 14);
    autoTable(doc, {
      head: [['Student ID', 'Student', 'Course', 'Class', 'Enrollment Date', 'Status', 'Term', 'Academic Year']],
      body: data.enrollments.map(item => [
        item.studentHumanId || item.studentId || 'N/A',
        item.studentName || 'N/A',
        item.courseName || 'N/A',
        item.className || 'N/A',
        item.enrollmentDate ? new Date(item.enrollmentDate).toLocaleDateString() : 'N/A',
        item.status || 'N/A',
        item.termName || 'N/A',
        item.academicYearName || 'N/A',
      ]),
      startY: (doc as any).lastAutoTable.finalY + 20,
      ...headerFooterOpts,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [66, 139, 202] },
    });

    // Fee Payments Table
    doc.text('Fee Payments Report', 14, (doc as any).lastAutoTable.finalY + 14);
    autoTable(doc, {
      head: [['Student ID', 'Student', 'Class', 'Amount', 'Payment Date', 'Payment Method', 'Status', 'Term']],
      body: data.feePayments.map(item => [
        item.studentHumanId || item.studentId || 'N/A',
        item.studentName || 'N/A',
        item.className || 'N/A',
        item.amount ? `$${item.amount.toLocaleString()}` : 'N/A',
        item.paymentDate ? new Date(item.paymentDate).toLocaleDateString() : 'N/A',
        item.paymentMethod || 'N/A',
        item.status || 'N/A',
        item.termName || 'N/A',
      ]),
      startY: (doc as any).lastAutoTable.finalY + 20,
      ...headerFooterOpts,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [66, 139, 202] },
    });

    doc.save('comprehensive-report.pdf');
  } catch (error) {
    console.error('Error generating comprehensive PDF:', error);
    throw new Error('Failed to generate comprehensive PDF report');
  }
};

export {
  generateStudentsPDF,
  generateTeachersPDF,
  generateCoursesPDF,
  generateEnrollmentsPDF,
  generateFeePaymentsPDF,
  generateComprehensivePDF,
  generateStudentsExcel,
  generateTeachersExcel,
  generateCoursesExcel,
  generateEnrollmentsExcel,
  generateFeePaymentsExcel,
  generateComprehensiveExcel,
};

// Backwards-compatible aggregate export (so existing code using reportService.* keeps working)
export const reportService = {
  generateStudentsPDF,
  generateTeachersPDF,
  generateCoursesPDF,
  generateEnrollmentsPDF,
  generateFeePaymentsPDF,
  generateComprehensivePDF,
  generateStudentsExcel,
  generateTeachersExcel,
  generateCoursesExcel,
  generateEnrollmentsExcel,
  generateFeePaymentsExcel,
  generateComprehensiveExcel,
};

// export {
//   generateStudentsPDF,
//   generateTeachersPDF,
//   generateCoursesPDF,
//   generateEnrollmentsPDF,
//   generateFeePaymentsPDF,
//   generateComprehensivePDF,
// };