
import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  FileHeart,
  Download,
  Calendar,
  Search,
  PlusCircle,
  FileText,
  DollarSign
} from "lucide-react";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { useAuth } from "@/contexts/AuthContext";
import { useNavigate } from "react-router-dom";

export default function FinanceReports() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const isFinanceUser = user?.role === 'finance';
  const [searchQuery, setSearchQuery] = useState("");

  // Redirect non-finance users
  if (!isFinanceUser) {
    navigate('/dashboard');
    return null;
  }

  // Sample report data
  const reports = [
    { id: 'REP001', name: 'Monthly Revenue Report', type: 'Revenue', period: 'Apr 2025', generatedBy: 'Sarah Wilson', status: 'completed' },
    { id: 'REP002', name: 'Term 2 Fees Collection', type: 'Collection', period: 'Q2 2025', generatedBy: 'Sarah Wilson', status: 'completed' },
    { id: 'REP003', name: 'Faculty Payroll Report', type: 'Expense', period: 'Apr 2025', generatedBy: 'System', status: 'completed' },
    { id: 'REP004', name: 'Annual Budget Review', type: 'Budget', period: '2025', generatedBy: 'Sarah Wilson', status: 'in-progress' },
    { id: 'REP005', name: 'Quarterly Financial Statement', type: 'Financial', period: 'Q1 2025', generatedBy: 'System', status: 'completed' },
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Financial Reports</h1>
          <p className="text-muted-foreground">
            Generate and view detailed financial reports
          </p>
        </div>
        
        <div className="flex space-x-2 mt-4 sm:mt-0">
          <Button onClick={() => {}}>
            <PlusCircle className="mr-2 h-4 w-4" />
            Generate New Report
          </Button>
          <Button variant="outline">
            <Calendar className="mr-2 h-4 w-4" />
            Schedule Reports
          </Button>
        </div>
      </div>

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle>Available Reports</CardTitle>
            <div className="flex items-center space-x-2">
              <div className="relative">
                <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                <Input
                  type="search"
                  placeholder="Search reports..."
                  className="pl-8 w-[200px] md:w-[300px]"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                />
              </div>
              <Button variant="outline" size="sm">
                <Download className="mr-2 h-4 w-4" />
                Export List
              </Button>
            </div>
          </div>
        </CardHeader>
        
        <CardContent>
          <Tabs defaultValue="all">
            <TabsList>
              <TabsTrigger value="all">All Reports</TabsTrigger>
              <TabsTrigger value="revenue">Revenue</TabsTrigger>
              <TabsTrigger value="expense">Expense</TabsTrigger>
              <TabsTrigger value="budget">Budget</TabsTrigger>
            </TabsList>
            
            <TabsContent value="all" className="mt-4">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Report ID</TableHead>
                    <TableHead>Name</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>Period</TableHead>
                    <TableHead>Generated By</TableHead>
                    <TableHead className="text-right">Status</TableHead>
                    <TableHead className="text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {reports.map((report) => (
                    <TableRow key={report.id}>
                      <TableCell className="font-medium">{report.id}</TableCell>
                      <TableCell>{report.name}</TableCell>
                      <TableCell>
                        <Badge variant="outline">{report.type}</Badge>
                      </TableCell>
                      <TableCell>{report.period}</TableCell>
                      <TableCell>{report.generatedBy}</TableCell>
                      <TableCell className="text-right">
                        <Badge variant={report.status === 'completed' ? 'default' : 'secondary'}>
                          {report.status === 'completed' ? 'Completed' : 'In Progress'}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-right">
                        <Button variant="ghost" size="sm">
                          <FileText className="h-4 w-4" />
                          <span className="sr-only">View</span>
                        </Button>
                        <Button variant="ghost" size="sm">
                          <Download className="h-4 w-4" />
                          <span className="sr-only">Download</span>
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TabsContent>
            
            <TabsContent value="revenue" className="mt-4">
              {/* Revenue reports content - similar structure */}
            </TabsContent>
            
            <TabsContent value="expense" className="mt-4">
              {/* Expense reports content - similar structure */}
            </TabsContent>
            
            <TabsContent value="budget" className="mt-4">
              {/* Budget reports content - similar structure */}
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
    </div>
  );
}
